package Todo.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptTodoItem = createDescriptorForTodoItem();
  /*package*/ final ConceptDescriptor myConceptTodoList = createDescriptorForTodoList();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptTodoItem, myConceptTodoList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.TodoItem:
        return myConceptTodoItem;
      case LanguageConceptSwitch.TodoList:
        return myConceptTodoList;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForTodoItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Todo", "TodoItem", 0x63767c0c5169449fL, 0x97fa815e269e5e13L, 0x5c704accc83d3bebL);
    b.class_(false, false, false);
    b.origin("r:19c21f3f-1b78-4ed4-a87c-f0955ee2e869(Todo.structure)/6660906092274203627");
    b.version(2);
    b.property("description", 0x5c704accc83d3bf0L).type(PrimitiveTypeId.STRING).origin("6660906092274203632").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTodoList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Todo", "TodoList", 0x63767c0c5169449fL, 0x97fa815e269e5e13L, 0x5c704accc83d3beaL);
    b.class_(false, false, true);
    b.origin("r:19c21f3f-1b78-4ed4-a87c-f0955ee2e869(Todo.structure)/6660906092274203626");
    b.version(2);
    b.property("name", 0x5c704accc83d3becL).type(PrimitiveTypeId.STRING).origin("6660906092274203628").done();
    b.aggregate("items", 0x5c704accc83d3beeL).target(0x63767c0c5169449fL, 0x97fa815e269e5e13L, 0x5c704accc83d3bebL).optional(true).ordered(true).multiple(true).origin("6660906092274203630").done();
    return b.create();
  }
}
